### PR TITLE
Add tests with unit tests module from micro-analytics-cli

### PR DESCRIPTION
**Pull request by relekang**
- [x] Upgrade micro-analytics-cli when it is released micro-analytics/micro-analytics#43

### CODE REVIEW

**Comment by relekang** [comment]
screenshot 2017-03-29 17 28 45

 @mxstbr Can you active [the travis job](https://travis-ci.org/micro-analytics/adapter-redis)?

**Comment by mxstbr** [comment]
Done, but also

screen shot 2017-03-29 at 22 10 27

**Comment by relekang** [comment]
Thanks @mxstbr it works now 🙌 

I forgot about the files properties in package.json, since it does not affect `npm  link` i did not notice it when testing locally. Will submit a new PR to micro-analytics later today.

**Comment by mxstbr** [comment]
Does it work?!

**Comment by relekang** [comment]
It works for node versions that supports async/await 😅

**Pull request merged**
