### PR TITLE
WIP: Add tests

### LINKED ISSUE #5: uhm, tests? 🤔
Should write some tests :v:

### PR DESCRIPTION
**Pull request by relekang**
Fixes #5

### CODE REVIEW

**Comment by mxstbr** [comment]
This fails currently right? (can we get a `.travis.yml` in here? I've approved the request.)

**Comment by mxstbr** [comment]
This fails in general, this doesn't work either:

```sh
npm install -g micro-analytics-cli micro-analytics-adapter-redis
DB_ADAPTER=redis micro-analytics
```

That throws the "no package found" error. I think this might not have to do with the test setup but with the adapter or core implementation of adapters?

**Comment by relekang** [comment]
The start command works fine with the stable release, but fails with this on 1.2.0-2. 🤔 

```
module.js:471
    throw err;
    ^

Error: Cannot find module 'update-notifier'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (~/.nvm/versions/node/v6.9.1/lib/node_modules/micro-analytics-cli/cli.js:4:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by relekang** [comment]
I added the travis config, but I think you must activate [the travis job](https://travis-ci.org/micro-analytics/adapter-redis)

**Comment by relekang** [comment]
@mxstbr I think this project needs to have mocha as a dependency as well?

**Comment by mxstbr** [comment]
No, I run `npm install` from `adapter-tests.js` so no dependencies are needed. (if I can manage to make it work, that is)

**Comment by relekang** [comment]
Then I guess we need to add `node_modules/micro-analytics/.bin` to path when running the tests?

**Comment by mxstbr** [comment]
I don't actually know how babel tries to get the presets. Will dig in!

**Comment by relekang** [comment]
Closing this for now. Think we need to do a bunch of changes when we are able to land integration tests.

**Pull request closed without merging**
